# Generated by Django 5.2.1 on 2025-05-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_uploadrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegexCallHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("prompt", models.TextField()),
                ("regex", models.TextField()),
                ("replacement", models.TextField()),
                ("column_name", models.CharField(max_length=100)),
                ("pattern_type", models.CharField(max_length=50)),
                ("called_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
