# Generated by Django 5.2.1 on 2025-05-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_regexcallhistory_delete_uploadedfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModifiedFileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                ("modified_data", models.JSONField()),
                ("regex", models.CharField(max_length=255)),
                ("replacement", models.TextField()),
                ("column_name", models.CharField(max_length=100)),
                ("pattern_type", models.CharField(default="custom", max_length=50)),
                ("prompt", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
