# Generated by Django 5.2.1 on 2025-05-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_modifiedfilerecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regexcallhistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Regex Call History",
                "verbose_name_plural": "Regex Call Histories",
            },
        ),
        migrations.RenameField(
            model_name="regexcallhistory",
            old_name="called_at",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="column_name",
            field=models.CharField(max_length=255, verbose_name="Column Name"),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="Error Message"),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="file_name",
            field=models.CharField(max_length=255, verbose_name="Source File"),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="pattern_type",
            field=models.CharField(
                default="custom", max_length=100, verbose_name="Pattern Type"
            ),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="prompt",
            field=models.TextField(verbose_name="Instruction"),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="regex",
            field=models.CharField(max_length=500, verbose_name="Regex Pattern"),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="replacement",
            field=models.CharField(max_length=500, verbose_name="Replacement Text"),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("failed", "Failed")],
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
