# Generated by Django 5.2.1 on 2025-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_regexcallhistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regexcallhistory",
            options={},
        ),
        migrations.RenameField(
            model_name="regexcallhistory",
            old_name="created_at",
            new_name="called_at",
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="column_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="file_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="pattern_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="prompt",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="regex",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="replacement",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="status",
            field=models.CharField(
                choices=[("success", "成功"), ("failed", "失败")],
                default="success",
                max_length=20,
            ),
        ),
    ]
