# Generated by Django 5.2.1 on 2025-05-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_regexcallhistory_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modifiedfilerecord",
            name="status",
            field=models.CharField(
                choices=[("success", "success"), ("failed", "failed")],
                default="success",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="regexcallhistory",
            name="status",
            field=models.CharField(
                choices=[("success", "success"), ("failed", "failed")],
                default="success",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="uploadrecord",
            name="status",
            field=models.CharField(
                choices=[("success", "success"), ("failed", "failed")], max_length=20
            ),
        ),
    ]
